use_frameworks!

platform :ios, '10.0'

target 'YUIKit_Example' do
  pod 'YUIArchitectureKit', :path => '../'

  target 'YUIKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
